- name: Backend Setup
  hosts: all
  become: yes
  tasks:
    - name: Install NodeJS, Add NodeSource Repository
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

    - name: Install NodeJS
      ansible.builtin.dnf:
        name: nodejs

    - name: Copy backend Service file
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: Add Application user
      ansible.builtin.user:
        name: expense

    - name: Cleanup old content
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download backend code and extract it
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
        remote_src: yes

    - name: Install NodeJS dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app

    - name: Install MySQL Client
      ansible.builtin.dnf:
        name: mysql

    - name: Load Schema
      ansible.builtin.shell: mysql -h mysql.ashudevops.online -uroot -p$ExpenseApp@1 < /app/schema/backend.sql

    - name: Start backend service
      ansible.builtin.systemd:
        name: restarted
        enabled: yes
        daemon-reload: yes
